### ISSUE TITLE
after minerva_deconvolve

### ISSUE THREAD

**Issue by fjruizruano** [dcdanko/minerva_barcode_deconvolution#10]
Hi @dcdanko !

I run the command you suggest in the README file for minerva_deconvolve and got my "ebc_assignments.tsv" file with 8 different clusters. My question is what analysis I can perform considering this information. An idea is to assembly separately the reads from each cluster. But have you some additional suggestion?

Thanks.

**Comment by dcdanko** [comment]
Hmm 8 clusters doesn't sound like very many. can you tell me about your data?

**Comment by fjruizruano** [comment]
I have a special dataset. I selected reads mapping with a specific part of a vertebrate genome and then extracted reads with the same 10XG barcode. My goal is to be able to assembly this part of the genome.

Another thing I noted is that my analysis started with ~400,000 reads and in the "ebc_assignments.tsv" file I only have ~6,500 lines.

**Comment by dcdanko** [comment]
Just to make sure I have your process right:
1. Map reads to a particular region
2. Find all barcodes from all reads in (1)
3. Find all reads from all barcodes in (2)
4. Run Minerva on (3)


The drop from 400,000 to 6,500 reads is likely due to Minerva's dropout threshold. By default barcodes with few reads are dropped. If you used the command on the README only barcodes with 20 reads or more would be in the output.

Given your situation 8 clusters might be reasonable. Minerva assumes that the chance of two overlapping fragments in two barcodes is low and as such struggles with small densely covered regions (individual microbial genomes do not seem to work well).

My hope would be that the 8 clusters you have map reads to some consistent region in the rest of your genome  which could be evidence of a structural rearrangement. We had talked about a similar use case when building Minerva but we never actually tested it.

**Comment by fjruizruano** [comment]
You understood perfectly what I did.

So, does it sound reasonable to assembly the reads from a single clusters separately?

Thanks.

**Comment by dcdanko** [comment]
I think that's unlikely to work. I know some linked-read systems would give full coverage of fragments but the standard 10X chemistry has fractional coverage and few overlaps within barcodes. Maybe try assembling all of the enhanced-barcodes/clusters together.

If you have time I'd recommend rerunning Minerva with a lower `dropout` and `anchor-dropout`.

**Comment by fjruizruano** [comment]
OK. Thanks a lot for the tips!
Now I know better how Minerva works and will try different parameters to get the best values for my data.
Bests.
